on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Install dependencies
        run: pacman -Syu --noconfirm git patch subversion
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        run: |
          git remote add upstream https://github.com/felixonmars/archriscv-packages.git
          git fetch upstream master
      - name: Test patch
        run: bash test.sh
